site_name: "de.NBI Cloud Wiki"                         
docs_dir: wiki
theme: bootstrap
pages:
  - 'Home' : 'index.md'
  - 'Portal' : 'Portal.md'
  - 'Quickstart' : 'quickstart.md'
  - 'Concept' : 
    - 'OpenStack Basics' : Concept/concepts.md
    - 'Security' : Concept/security.md
  - 'Tutorials' :
    - 'Bibigrid' : Tutorials/BiBiGrid/index.md
    - 'Blast on BiBiGrid' : Tutorials/BlastOnBiBiGrid/index.md
    - 'Object Storage' : Tutorials/ObjectStorage/index.md
    - 'UserData' : Tutorials/UserData/index.md
  - 'FAQ' : 'FAQ.md'
  - 'Compute Center Specific' :
    - 'Giessen' : Compute_Center/Giessen.md
    - 'Bielefeld' : Compute_Center/Bielefeld.md
    - 'Heidelberg' : Compute_Center/Heidelberg.md
    - 'Tuebingen' : Compute_Center/Tuebingen.md
    - 'Freiburg' : Compute_Center/Freiburg.md
